### PR TITLE
feat: automatic release notes

### PR DESCRIPTION
**Pull request by elihwyma**
Adds a flag to automatically generate release notes using the JSON flag provided by GitHub.

### CODE REVIEW

**Comment by drogelfever** [comment]
My team and I are very interested in this use case. We would definitely use it in our CI/CD workflows if it was available. @BirmacherAkos is there anything you need from our side to review and approve the PR? Who should we notify to get this PR reviewed?

Thanks!!

**Comment by cpaleop** [comment]
👋🏻 Hey, that would be a very nice addition indeed!

**Comment by RileyGB** [comment]
Please merge this PR!

**Review by RileyGB — APPROVED** [review]

**Comment by OmarJalil** [comment]
Any release date? Looking forward to use it!

**Comment by FaggioniHQ** [comment]
Any release date?. thanks in advance

**Review by godrei — APPROVED** [review]

**Comment by godrei** [comment]
Hi @elihwyma thank you for this PR and sorry for the late response.
I had to commit some changes to modernize the step and also set the `generate_release_notes` step input to `no` by default so that we don't introduce a breaking change.

**Pull request merged**
